name: buy_me_a_coffee_widget
description: Did you ever needed a widget for buy me a coffee, well here it is.
version: 2.0.0-nullsafety.0
homepage: https://github.com/md-weber/buy_me_a_coffee

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  google_fonts: ^4.0.5
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  assets:
    - assets/fonts/
